pipeline:
  - __type__: cobald.controller.linear.LinearController
    low_utilisation: 0.90
    high_allocation: 0.90
    rate: 1
  - __type__: cobald.decorator.limiter.Limiter
    minimum: 1
    maximum: 1000
  - __type__: cobald.decorator.logger.Logger
    name: 'changes'
  - __type__: tardis.resources.poolfactory.create_composite_pool
logging:
  version: 1
  root:
      level: DEBUG
      handlers: [console, file]
  formatters:
    precise:
      format: '%(name)s: %(asctime)s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class : logging.StreamHandler
      formatter: precise
      stream  : ext://sys.stdout
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: precise
      filename: tardis.log
      maxBytes: 10485760
      backupCount: 3
tardis:
  Plugins:
    SqliteRegistry:
      db_file: drone_registry.db
  
  BatchSystem:
    adapter: FakeBatchSystem
    allocation: 1.0
    utilization: 1.0
    machine_status: Available
  
  Sites:
    - name: GridKa
      adapter: HTCondor
      quota: 10 # CPU core quota
  
  GridKa:
    max_age: 1
    MachineTypes:
      - m1.small
      - m8.small
    MachineTypeConfiguration:
      m1.small:
        jdl: submit.jdl
      m8.small:
        jdl: submit.jdl
    MachineMetaData:
      m1.small:
        Cores: 1
        Memory: 2
        Disk: 10
      m8.small:
        Cores: 8
        Memory: 16
        Disk: 80
